//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenGov.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fleet
    {
        public string Agency { get; set; }
        public Nullable<double> Report_Year { get; set; }
        public string Disposed { get; set; }
        public Nullable<double> Equipment_Number { get; set; }
        public string Category { get; set; }
        public Nullable<double> Model_Year_ { get; set; }
        public string Make_Model { get; set; }
        public string VIN { get; set; }
        public string License_Plate_Number { get; set; }
        public Nullable<double> Postal_Code { get; set; }
        public string Vehicle_Type_Desc { get; set; }
        public string Weight_Class { get; set; }
        public string Passenger_Vehicle_On_Off_Road_Owned_Leased { get; set; }
        public Nullable<double> Payload_Rating { get; set; }
        public Nullable<double> Shipping_Weight { get; set; }
        public string Wheel_Type { get; set; }
        public string Tire_Size { get; set; }
        public string Fuel_Type { get; set; }
        public string Engine_Configuration { get; set; }
        public string Emissions_Type { get; set; }
        public string Primary_Application { get; set; }
        public string Secondary_Application { get; set; }
        public Nullable<System.DateTime> Acquisition_Delivery_Date { get; set; }
        public string SUV_Justification { get; set; }
        public string ID4X4_Justification { get; set; }
        public string Acquisition_Method_Reason { get; set; }
        public Nullable<decimal> Purchase_Price { get; set; }
        public Nullable<decimal> Annul_Lease_Rate { get; set; }
        public Nullable<double> Acquistion_Mileage { get; set; }
        public Nullable<System.DateTime> Disposition_Date { get; set; }
        public string Transferred_To { get; set; }
        public string Disposition_Method { get; set; }
        public string Disposition_Reason { get; set; }
        public Nullable<double> Disposition_Mileage { get; set; }
        public Nullable<decimal> Disposition_Sold_Amount { get; set; }
        public string Fuel_Total_Fuel_Average { get; set; }
        public string Fuel_Total { get; set; }
        public string Fuel_Average { get; set; }
        public string Total_Miles { get; set; }
        public string Dec_Prior_Year_ { get; set; }
        public int Id { get; set; }
    }
}
